server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/pipelines?reWriteBatchedInserts=true
